# Generated by Django 5.2.8 on 2025-11-18 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="survey.question",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="user_id",
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
